[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api*"
  to = "https://plza-app.herokuapp.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
